# Generated by Django 4.2.3 on 2023-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_id_projects_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='desp',
            field=models.TextField(max_length=400),
        ),
    ]
