# Generated by Django 4.2.3 on 2023-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_projects_desp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url_code',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url_repo',
            field=models.URLField(blank=True),
        ),
    ]
